{
 "title": "APM Sessions",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_apm_sessions_current,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling APM Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "APM Metrics are not enabled in the OpenTelemetry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable APM metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.apm:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable APM metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.apm:\n      enabled: true\n```"
   }
  },
  {
   "title": "Current APM Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_apm_sessions_current{job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_type}}"
    }
   ]
  },
  {
   "title": "APM Session Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "f5_apm_sessions_current{job=~\"$device_name\"} / f5_apm_sessions_limit{job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_type}}"
    }
   ]
  },
  {
   "title": "Current APM Access Sessions By State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "f5_apm_access_sessions_current{job=~\"$device_name\"}",
     "legendFormat": "{{job}} - {{f5_apm_session_state}}"
    }
   ]
  },
  {
   "title": "APM Access Sessions Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(f5_apm_access_sessions_current{job=~\"$device_name\"}) by (job) / sum(f5_apm_access_sessions_limit{job=~\"$device_name\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "CGNAT",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_cgnat_lsn_pool_generation,job)"
    }
   },
   {
    "name": "pool",
    "label": "LSN Pool",
    "query": {
     "query": "label_values(f5_cgnat_lsn_pool_generation{job=~\"$device_name\"},f5_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling CGNAT Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "CGNAT Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable CGNAT metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.cgnat:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable CGNAT metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.cgnat:\n      enabled: true\n```"
   }
  },
  {
   "title": "LSN Pool Settings",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_pba_info{job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Translations (Current)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_translations_current{job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Active Port Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "f5_cgnat_lsn_pool_pba_port_blocks_active{job=~\"$device_name\", f5_pool_name=~\"$pool\"}",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Translation Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_translations_requests_total{job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Port Block Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_pba_port_blocks_allocations_total{job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "Pool Translation Request Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_translations_requests_total{job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  },
  {
   "title": "PBA Port Block Allocation Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(f5_cgnat_lsn_pool_pba_port_blocks_allocation_failures_total{job=~\"$device_name\", f5_pool_name=~\"$pool\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{f5_pool_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Device Utilization",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_system_state_up_ratio,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. CPU Utilization ",
   "type": "timeseries",
   "description": "Avg Utilization Across All CPUs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job) (f5_system_cpu_utilization_ratio{job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Mem Utilization ",
   "type": "timeseries",
   "description": "Avg System Memory Used",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(job) (f5_system_memory_used_bytes{job=~\"$device_name\", state=\"used\"}) / avg by(job) (f5_system_memory_total_bytes{job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(f5_system_logical_disk_usage_bytes{job=~\"$device_name\", state=~\"free\"} * 1000000) by (job, f5_system_logical_disk_name) /sum(f5_system_logical_disk_limit_bytes{job=~\"$device_name\"}) by(job, f5_system_logical_disk_name)",
     "legendFormat": "{{job}} ({{f5_system_logical_disk_name}})"
    }
   ]
  },
  { "title": "Configuration Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Configured Virtual Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (f5_virtual_server_info{job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Pools",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (f5_pool_info{job=~\"$device_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Pool Members",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "count by(job) (sum by(job, f5_pool_member_name) (f5_pool_member_enabled_ratio{job=~\"$device_name\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Aggregate Virtual Server Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Current Client Side Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(job) (f5_virtual_server_clientside_connection_count{job=~\"$device_name\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Side Data Rate In/Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8*sum by(job) (rate(f5_virtual_server_clientside_bytes_in_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - In"
    },
    {
     "expr": "-8*sum by(job) (rate(f5_virtual_server_clientside_bytes_out_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - Out"
    }
   ]
  }
 ]
}
{
 "title": "DoS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_dos_attacks_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling DoS Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "DoS Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable DoS metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.dos:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable DoS metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.dos:\n      enabled: true\n```"
   }
  },
  {
   "title": "DoS Profile Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "f5_profile_dos_info{job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_stats_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Attacks Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_attacks_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_drops_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Stats By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_stats_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Attacks By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_attacks_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS Drops By Vector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(f5_dos_vector_name) (rate(f5_dos_drops_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DoS BA Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_stats_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BA Detected Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_detected_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BA Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_ba_drops_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Stats Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_stats_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Detected Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_detected_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS BD Drops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum by(job) (rate(f5_dos_bd_drops_total{job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(f5_dos_bytes_total{job=~\"$device_name\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DoS Byte Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(f5_dos_bytes_drops_total{job=~\"$device_name\"}[$__rate_interval]))  by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "Firewall",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_firewall_rule_hits_total,job)"
    }
   },
   {
    "name": "context",
    "label": "Context",
    "query": {
     "query": "label_values(f5_firewall_rule_hits_total{job=~\"$device_name\"},f5_firewall_rule_context_name)"
    }
   },
   {
    "name": "rule_name",
    "label": "Rule Name",
    "query": {
     "query": "label_values(f5_firewall_rule_hits_total{job=~\"$device_name\"},f5_firewall_rule_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Enabling Firewall Rule Metrics",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Firewall Rule Metrics are not enabled in the Opentelemtry Collector by default\n(due to the relatively large number of requests required to gather the data).\n\n\nFor data to populate in this dashboard, you need to enable them as follows (and then you might want\nto delete this panel):\n\n## Enable For All BigIPs\nYou can enable Firewall Rule metrics for all BigIPs by editing the\nconfig/ast_defaults.yaml file in the AST directory and setting\n\n```yaml\nbigip_receiver_defaults:\n...\n  data_types:\n...\n    f5.firewall:\n      enabled: true\n```\n\n## Enable For Select BigIPs\nYou can enable Firewall Rule metrics for specific BigIPs by editing the\nconfig/bigip_receivers.yaml file and setting the flag for the\nspecific devices you need:\n\n```yaml\nbigip/1:\n  endpoint: https://10.0.0.1\n  data_types:\n    f5.firewall:\n      enabled: true\n```"
   }
  },
  {
   "title": "Firewall Rule Hit Rate By Action & Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(f5_firewall_rule_action, f5_firewall_rule_stat_type) (rate(f5_firewall_rule_hits_total{job=~\"$device_name\", f5_firewall_rule_context_name=~\"$context\", f5_firewall_rule_name=~\"$rule_name\"}[$__rate_interval]))",
     "legendFormat": "Action: {{f5_firewall_rule_action}} ({{ f5_firewall_rule_stat_type }})"
    }
   ]
  },
  {
   "title": "Firewall Rule Hits Last 1H",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(f5_firewall_rule_hits_total{job=~\"$device_name\", f5_firewall_rule_context_name=~\"$context\", f5_firewall_rule_name=~\"$rule_name\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Fleet Inventory",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Inventory Total By Software Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info) by (system_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Total By Product Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info) by (system_product_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Total By Product Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_system_info) by (f5_system_marketing_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Inventory By Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(f5_system_info)  by (system_version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Module Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "f5_module_provision_generation{level!=\"none\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inventory Detail",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "f5_system_info", "legendFormat": "__auto" },
    {
     "expr": "f5_system_failover_peer_active_state_ratio",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Virtual Servers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "virtual_server",
    "label": "Virtual Server",
    "query": {
     "query": "label_values(f5_virtual_server_info,f5_virtual_server_name)"
    }
   },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(f5_virtual_server_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Virtual Server Availability [24h]",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", availability_state=\"available\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"offline\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h]) / count_over_time(f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"unknown\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h]) / count_over_time(f5_virtual_server_enabled_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VS isAvailable",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "f5_virtual_server_availability_ratio{job=~\"$device_name\", f5_virtual_server_name=~\"$virtual_server\", availability_state=\"available\"}",
     "legendFormat": "{{job}} {{ f5_virtual_server_name }}"
    }
   ]
  },
  {
   "title": "VS Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(f5_virtual_server_clientside_connection_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}}"
    }
   ]
  },
  {
   "title": "VS Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(f5_virtual_server_clientside_bytes_in_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}} - In"
    },
    {
     "expr": "-8 * rate(f5_virtual_server_clientside_bytes_out_total{f5_virtual_server_name=~\"$virtual_server\"}[$__rate_interval])",
     "legendFormat": "{{job}} {{f5_virtual_server_name}} - Out"
    }
   ]
  },
  {
   "title": "Fleet Virtual Server Details",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "f5_virtual_server_info{f5_virtual_server_name=~\"$virtual_server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(f5_virtual_server_generation{f5_virtual_server_name=~\"$virtual_server\", job=~\"$device_name\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "SSL Certificate Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "# SSL Certificate Status\n\nThis dashboard displays information about SSL Certificates associated with a BigIP Device.\nData collected includes (only) the following:\n\n* Certificate Name\n* Certificate Expiration Time\n* Certificate Key Type\n* Whether the certificate is part of a bundle"
   }
  },
  {
   "title": "Certificate Type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_ssl_certificate_expires_at) by (key_type)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 30 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at - time() < 86400 * 30)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 90 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at - time() < 86400 * 90)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  {
   "title": "Expires < 180 Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(f5_ssl_certificate_expires_at -time() < 86400 * 180)",
     "legendFormat": "{{key_type}}"
    }
   ]
  },
  { "title": "Certificate Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(f5_ssl_certificate_expires_at) - time()",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}