{
 "title": "OpenTelemetry Collector",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics (tested with OTEL contrib v0.101.0)",
 "tags": [
  "opentelemetry",
  "monitoringartist"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(otelcol_process_memory_rss,job)"
    }
   },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   {
    "name": "receiver",
    "label": "Receiver",
    "query": {
     "query": "query_result(avg by (receiver) ({__name__=~\"otelcol_receiver_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "query_result(avg by (processor) ({__name__=~\"otelcol_processor_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "query_result(avg by (exporter) ({__name__=~\"otelcol_exporter_.+\",job=\"$job\"}))"
    }
   },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By service instance id : \\,service_instance_id"
   },
   {
    "name": "suffix",
    "label": "Suffix",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime.+\",job=\"$job\"})"
    }
   },
   { "name": "adhoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metric Points Receive ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_metric_points${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_metric_points${suffix}{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points Export ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric_points${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric_points${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric_points${suffix}{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Send Size Heatmap",
   "type": "heatmap",
   "description": "Number of units in the batch",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(otelcol_processor_batch_batch_send_size_bucket{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batch Metrics 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_count{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch send size count: {{processor}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_sum{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch send size sum: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Batch Metrics 2",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a size trigger. Number of times the batch was sent due to a timeout trigger.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_size_trigger_send${suffix}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a size trigger: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger_send${suffix}{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "description": "Current size of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{exporter=~\"$exporter\",job=\"$job\"}) by (exporter $grouping)",
     "legendFormat": "Max queue size: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity",
   "type": "timeseries",
   "description": "Fixed capacity of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(otelcol_exporter_queue_capacity{exporter=~\"$exporter\",job=\"$job\"}) by (exporter $grouping)",
     "legendFormat": "Queue capacity: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\r\n    otelcol_exporter_queue_size{\r\n        exporter=~\"$exporter\", job=\"$job\"\r\n    }\r\n) by (exporter $grouping)\r\n/\r\nmin(\r\n    otelcol_exporter_queue_capacity{\r\n        exporter=~\"$exporter\", job=\"$job\"\r\n    }\r\n) by (exporter $grouping)",
     "legendFormat": "Queue capacity usage: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total RSS Memory",
   "type": "timeseries",
   "description": "Total physical memory (resident set size)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Sys Memory",
   "type": "timeseries",
   "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Heap Memory",
   "type": "timeseries",
   "description": "Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu_seconds${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min(rate(otelcol_process_cpu_seconds${suffix}{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "description": "Number of service instances, which are reporting metrics",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id))",
     "legendFormat": "Service instance count"
    }
   ]
  },
  {
   "title": "Uptime by Service Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id)",
     "legendFormat": "Service instance uptime: {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime${suffix}{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id,service_name,service_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC server/client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC server responses by GRPC status code (receivers)",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC. Should be 1 for all non-streaming RPCs. GRPC status codes: https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum by(rpc_grpc_status_code) (${metric:value}(otelcol_rpc_server_responses_per_rpc_count{}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC client responses by GRPC status code (exporters)",
     "type": "timeseries",
     "description": "Measures the number of messages received per RPC. Should be 1 for all non-streaming RPCs. GRPC status codes: https://grpc.github.io/grpc/core/md_doc_statuscodes.html",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum by(rpc_grpc_status_code) (${metric:value}(otelcol_rpc_client_responses_per_rpc_count{}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC server duration (receivers)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(otelcol_rpc_server_duration_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC client duration (exporters)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(otelcol_rpc_client_duration_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC server request size (receivers)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(otelcol_rpc_server_request_size_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RPC client request size (exporters)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(otelcol_rpc_client_request_size_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespaces",
     "type": "timeseries",
     "description": "Added: Number of namespace add events received.\nUpdated: Number of namespace update events received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_added${suffix}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_updated${suffix}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "description": "Added: Number of pod add events received.\nUpdated: Number of pod update events received.\nDeleted: Number of pod delete events received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_added${suffix}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_updated${suffix}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{service_instance_id}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_deleted${suffix}{job=\"$job\"}) by (job $grouping)",
       "legendFormat": "Deleted: {{transport}} {{service_instance_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics\">OTEL collector troubleshooting (how to enable telemetry metrics)</a> | \n<a target=\"_blank\" href=\"https://opentelemetry.io/docs/collector/scaling/\">Scaling the Collector (metrics to watch)</a> | \n<a target=\"_blank\" href=\"https://opentelemetry.io/docs/collector/internal-telemetry/\">Collector internal telemetry</a> | \n<a target=\"_blank\" href=\"https://www.otelbin.io/\">OTelBin (OpenTelemetry collector configuration tool)</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "BigIP Collector Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "endpoint",
    "label": "API Endpoint",
    "query": {
     "query": "label_values(endpoint_scrape_requests_total,endpoint)"
    }
   },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "label_values(scrape_duration_seconds{job=~\"bigip.*\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Full Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"bigip.*\", job=~\"$device_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Endpoint Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "endpoint_scrape_duration_seconds{path=~\"$endpoint\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} {{path}}"
    }
   ]
  },
  {
   "title": "Status Per Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "endpoint_scrape_responses_total{path=~\"$endpoint\", job=~\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Responses Rate By Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(endpoint_scrape_responses_total{path=~\"$endpoint\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Size Bytes (by endpoint)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_scrape_response_size_bytes{path=~\"$endpoint\", job=~\"$device_name\"}",
     "legendFormat": "{{job}} {{path}}"
    }
   ]
  },
  {
   "title": "API Requests By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(path, job) (rate(endpoint_scrape_requests_total{path=~\"$endpoint\", job=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "{{job}}: {{path}}"
    }
   ]
  }
 ]
}