apiVersion: v1
kind: Secret
metadata:
  name: otel-env
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
  SENSOR_SECRET_TOKEN: "YOUR_TOKEN"
  SENSOR_ID: "YOUR_ID"

